--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/aieuo/if_plugin
branches:
- master
projects:
  if_plugin:
    path: ""
    libs:
      - src: fuyutsuki/libform/libform
        version: 0.4.0
...
