---
name: if
main: aieuo\ip\IFPlugin
version: 3.6.4
api: 3.0.0
load: POSTWORLD
author: aieuo
permissions:
  ifplugin.customcommand.op:
    default: op
    description: "ifplugin.customcommand.op"
  ifplugin.customcommand.true:
    default: true
    description: "ifplugin.customcommand.true"
...