---
name: if
main: aieuo\ip\ifPlugin
version: 3.1.0
api:
- 3.0.0
- 4.0.0
load: POSTWORLD
author: aieuo
permissions:
  ifplugin.customcommand.op:
    default: op
    description: "ifplugin.customcommand.op"
  ifplugin.customcommand.true:
    default: true
    description: "ifplugin.customcommand.true"
...